### ISSUE TITLE
[meta] Use correct buckets for `main_summary` dependencies when running in dev/staging

### ISSUE THREAD

**Issue by acmiyaguchi** [mozilla/telemetry-airflow#316]
I wanted to verify the `main_summary` dag to test #297 of making the default EMR release 5.13.0. I followed the instructions added in #295 for running the `main_summary` dag, but I noticed that there are quite a few jobs that don't accept the right input bucket from the environment.
 
- [x] #308 engagement_ratio
- [x] #309 addon_aggregates
- [x] #310 experiment_aggregates (?)
- [x] #311 search_dashboard / search_clients_daily
- [x] #312 clients_daily (also possibly deprecated)
- [x] #313 clients_daily_v6
- [x] #314 retention
- [x] #315 client_count_daily_view
- [x] experiments_error_aggregates

Fixing these would make this dag moderately better for testing locally for testing end-to-end changes. Some issues look like they require slightly more effort than others.

**Comment by acmiyaguchi** [comment]
I'm fairly confident running the main_summary DAG after PR #326 should be isolated from our production environment. It may be good to isolate this at a IAM level, to prevent users from accidentally overwriting production data.
